### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BioBut** [AryanBisht-03/Whatsapp_Status_downloader#1]
MIT license or apache license

**Comment by AryanBisht-03** [comment]
I don't have any license for it and don't knw how to apply for this thing.!!
If you can help me to license it please let me know.

**Comment by BioBut** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

please check  and  suitable license  apache license

**Comment by AryanBisht-03** [comment]
Thanks for the help I merged your code.
